### ISSUE TITLE
changing models

### ISSUE THREAD

**Issue by biowaea** [s4afa451dgf415f/colab_stable_diffusion#12]
ı didnt  found a way to change models 
ı have some models on my drive but ı cant found a way to change in google colab

**Comment by s4afa451dgf415f** [comment]
in fact,you need build a fold named "checkpoint" or "lora" move it to fold. you should skim the english document to find the detailes.

**Comment by biowaea** [comment]
yeah ı add download link and save after ı add with saved model name and its worked
