### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/content/stable-diffusion-webui/embeddings'

### ISSUE THREAD

**Issue by gaozhangmin** [s4afa451dgf415f/colab_stable_diffusion#2]
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-16-d8f3f110ab17>](https://localhost:8080/#) in <cell line: 108>()
    106 get_ipython().run_line_magic('cd', '/content/{sd}')
    107 import shutil
--> 108 shutil.rmtree(f'/content/{sd}/embeddings')
    109 get_ipython().system('git clone https://huggingface.co/nolanaatama/embeddings')
    110 

1 frames
[/usr/lib/python3.10/shutil.py](https://localhost:8080/#) in rmtree(path, ignore_errors, onerror)
    711         # lstat()/open()/fstat() trick.
    712         try:
--> 713             orig_st = os.lstat(path)
    714         except Exception:
    715             onerror(os.lstat, path, sys.exc_info())

FileNotFoundError: [Errno 2] No such file or directory: '/content/stable-diffusion-webui/embeddings'

**Comment by s4afa451dgf415f** [comment]
it should fix the error.
