### ISSUE TITLE
关于谷歌的针对的自动断开

### ISSUE THREAD

**Issue by GENTTAS** [s4afa451dgf415f/colab_stable_diffusion#20]
运行最后的单元格 超过7-8分钟目前就会断开,但是不会提示挖矿。有什么办法解决么

**Comment by Benson80** [comment]
function ConnectButton(){
console.log("Connect pushed");
document.querySelector("#top-toolbar > colab-connect-button").shadowRoot.querySelector("#connect").click()
}
setInterval(ConnectButton,60000);

**Comment by s4afa451dgf415f** [comment]
已经修复了，你再试下。

**Comment by s4afa451dgf415f** [comment]
> function ConnectButton(){ console.log("Connect pushed"); document.querySelector("#top-toolbar > colab-connect-button").shadowRoot.querySelector("#connect").click() } setInterval(ConnectButton,60000);

I think it's probably due to Google's server issues

**Comment by s4afa451dgf415f** [comment]
> function ConnectButton(){ console.log("Connect pushed"); document.querySelector("#top-toolbar > colab-connect-button").shadowRoot.querySelector("#connect").click() } setInterval(ConnectButton,60000);

我觉得大概是谷歌服务端的原因

**Comment by GENTTAS** [comment]
谢谢dalao

**Comment by biowaea** [comment]
15-20分钟后它仍然关闭...

**Comment by Benson80** [comment]
过几分钟还是断开，Google Colab可以稳定不断开吗？需要白嫖几小时

**Comment by 01Evin** [comment]
还是不行 最后一步会断开，太难了

**Comment by s4afa451dgf415f** [comment]
啊？我测了一个号是跑到时间的，我再看看把。

**Comment by s4afa451dgf415f** [comment]
看下好了没，

**Comment by 01Evin** [comment]
> 看下好了没，
可以，目前链接20分钟还没断，就是云盘的模型和插件好像没连上，自己看看是不是路径问题

**Comment by GENTTAS** [comment]
谢谢dalao,跑了20分钟没断开. 随后把插件复制到文件夹没反应.然后又接着跑了10分钟,没有断开.启动的时候没有加载插件.

**Comment by 01Evin** [comment]
> > 看下好了没，
> > 可以，目前链接20分钟还没断，就是云盘的模型和插件好像没连上，自己看看是不是路径问题

我看Colab是有显示我的模型文件和插件的，就是没加载出来

**Comment by s4afa451dgf415f** [comment]
更了，重新打开，编辑器全选出了一点问题。

**Comment by GENTTAS** [comment]
今天好像又不行了,出现了前几个单元格类似也会出现直接也会出现断开的情况

**Comment by 01Evin** [comment]
> 更了，重新打开，编辑器全选出了一点问题。

今天确实会断，试了好几次

**Comment by GENTTAS** [comment]
主要是运行最后的单元格会断开,没有任何提示挖矿.测了一下不运行最后的单元格没事.

PRO号一切正常 怎么开都不会断。

**Comment by s4afa451dgf415f** [comment]
主要是谷歌那里又更新了，暂时更了，重新打开。周末我整体弄下。

**Comment by 01Evin** [comment]
> 主要是谷歌那里又更新了，暂时更了，重新打开。周末我整体弄下。

好的 辛苦了

**Comment by GENTTAS** [comment]
谢谢dalao抽空来修这个 辛苦了

**Comment by Benson80** [comment]
如何在手机端稳定不断开？发自我的手机-------- 原始邮件 --------发件人： DingdongChicken ***@***.***>日期： 2023年9月15日周五 19:10收件人： s4afa451dgf415f/colab_stable_diffusion ***@***.***>抄送： Benson80 ***@***.***>, Comment ***@***.***>主    题： Re: [s4afa451dgf415f/colab_stable_diffusion] 关于谷歌的针对的自动断开 (Issue #20)
主要是谷歌那里又更新了，暂时更了，重新打开。周末我整体弄下。

**Comment by cym31153** [comment]
这是什么原理，是谷歌针对这个项目整体还是只针对几个关键词，如果整体的话能不能随便加几句废话进去破解谷歌的限制

**Comment by s4afa451dgf415f** [comment]
整体弄了下，测了两个都能用。好像我主号进了白名单之前没测出来？

**Comment by GENTTAS** [comment]
强的👍,试了下确实解决了

**Comment by 01Evin** [comment]
`Status Legend:
(OK):download completed.
aria2c完成下载耗时： 63.604480266571045 秒
Cloning into '/libx32/295isO/embeddings'...
remote: Enumerating objects: 61, done.
remote: Total 61 (delta 0), reused 0 (delta 0), pack-reused 61
Unpacking objects: 100% (61/61), 7.62 KiB | 557.00 KiB/s, done.
could not make way for new symlink: sd-webui-3d-open-pose-editor
could not make way for new symlink: sd-webui-controlnet
could not make way for new symlink: sd-webui-lora-block-weight
could not make way for new symlink: sd-webui-prompt-all-in-one
could not make way for new symlink: stable-diffusion-webui-localization-zh_CN
cannot delete non-empty directory: sd-webui-3d-open-pose-editor
cannot delete non-empty directory: sd-webui-controlnet
cannot delete non-empty directory: sd-webui-lora-block-weight
cannot delete non-empty directory: sd-webui-prompt-all-in-one
cannot delete non-empty directory: stable-diffusion-webui-localization-zh_CN
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
已加载云盘里的插件
已加载云盘里的VAE
已加载云盘里的embeddings
Traceback (most recent call last):
  File "/content/main2.py", line 2, in <module>
    exec(zlib.decompress(base64.b64decode('eJztWl9rI8kRf/enGOZFcnDPaGTJ6yzowdje5cD2Gq/PHBgztGZ6pEY93XPdPbJ0i+EIueQuu3eX3MuFTSB5SyCwgQQu4ZLLp1mvb5/yFVI9+mdJlizJYmFNjBmPu6uqf7/q6qqemaZxIqS2JOahiFdo5z+lJeW1/n9pNZEiIEr1W9r9W9G/CwQPUikJ106U6lSSfo+mMemr1lNN2UqCJY5V5dnFSiSkhWXNotyYdeC2eeo9PHu4YtHIdDhKY6nVOdX1fA6h3Cr0WA3S9puYpaQCEqeM8G7XmaMSRnU+V8mtghhYMH196dVKpWjUjf5aR7/fZ5o7qE6h7azSaRxwd2TK81EuCK1nXTE7pNI+u3Bza6pOGKscSxhhBcbs9afUPqtUbMxxwgV588XzN7///uovf7189eLqP1+9/fRnbz/70gY4Y2PUKHiTCU6sutaJeui60FJPq04gYrdrzQW3VBlBIY2iVFHB0TmppnQU3DA2wsbRbX14/GR/6/iDbQ9+Lr/6w9UXnzc9Z90p5K/+/PfLVy9Xb4GIqlZH3kJIQdQApipEU1C/CfzQYAtSUGQWQGXHezeAgjoJGomgXPupZJVn9g6WDV+lqk79mLYchSOiCVdCKvuh3YNQT2s1wBbhgAAONw4ZiqmUQrohqKNMHVpaLiwjwZrEjTHlWd9T07VPW/DrVyWt1TWRQ4Os2Vu8retg/aR8su43y4dSH+3OhgOYaIiwjjpqlp3CMIBbLa/ZQZ0yJlIN4P0DegizQ8JHibfxaFZfcCy4aHL3ZkPrxUejXpkiOIJNJjX/pDQbjC2OzTS7oDM83NHhY3RSQvsiJAztiHPOBA6z1mZpZLxDKbR4TLj/UdnZREmGDEXgjNkgmOlWWsi46JULbmasBsZaYMx/EkU0oJj5R4QRrMgwxtkGXrM5LBgY375YCUlkgZgPa8MPu6TyJtdm6dc3KbxiLo655FfnzVqH9TYw4a4KO2sKMIk40QgzhihHRms0rZKWwQmrUE3RGl6Lc4Lap420CrEzsA81TEvBONEzwRmI3wlHqBmHlX9z9kFMBJjRT7A2TZ/U/e2DqdhmNXInxFEj5dxbL264IiE8EYogElII1WnQRkTvBGBHxJTTxo4wFdHkbtSfFI1rIJEwCPNpaCZr3QnYtmgLTdCWmzJYKRhu00SB7wmCjQ7CqRbQSAMz+DR0o9p3wgTOpliLSbFxHnolw79Gpk7f7dp3AgmpCH4hSSSD9bUeIhM0aMYAm6Z3J2x13BBQjRv4WgJjQmJUhXXVgAZThmdCNqY1govw8IZcm8B2XOfty3/87fKz529f/gKg/fjpt2++/e6//35pr/V00CBVr9lXf/rGXu1ndQwBUAwWTOwdZdhNQbqDGkOARA0x0iSsQsyWxULQ2bK8DQup7NqwvH3r2fDG6LTnnNjUTfvs7MJC41vprFO5T0dCzUJiINo1cHHbjC4Ge9LGSMRRG0OAtmORKljlWeI/IBo1PeT5prT610rryAalI+03PY/4KvTKPk2KiT9aj6c4ZDCeccXN9q6bei99E3lJh01IEl1finuGTb73HuqSCTDn7aX457rB++IdyhNsks4S/dM1eV88xCgnJvf/f4VN8lDMVLjMADL27otv4FElxqyKyTId1Dd6X7zUe9hZppN6Nu+Lj1QgaRU2esv0Uc/mvfERqS3VPaR2bzwjIk3C2nKjp2vznvhIFfu1HnN4vFuiq0ZNv/cei3rPUpouKSNNt/hOncREY/sjt9RCHzItsapjmQw7otf11HQ5sJObQnj36dHjrQPXsB1Te6esQqyxIlrBDVahu33gBKo5zKvTdhOZmV4FunCvDNGOnXle1nSYXr568ebzX7/+5/Mff/hh9lc2QSrZYi9rbKNqoT1h5XqEc0A4N5i9k61dt4kJijSKFUGbpQL8IBLj7meCoRid5HnzLpAyqtuYmndb1+wJSUEQs+FpmHVAe3r4zMauwVC0ibKsVHTMF62JNOq4kUpC3XNMo/Tam03IHKU+gVJQigplr1AqlMtBofhTHJYfPAi8TRx4DzZKG8WoEHohNBiS42MvhVFmD8w7U7ioc4a6KkbcgBmagms27DnC2OBbLIjPa2SxT0k2TrRFOUgzZjFaTfk55eEmCgks5PbHH4/AF8ohvEml4Kf23o5/eLS792Rrxz6r2KCrA3isYCJwlHBK9rDw8SN/+/DQ3//gwN978tjf2z3Z3TNq6/Y4JJWGwgJcCEj1sSnRsqIoTkjNwAwwmC0O7gzeeTxt/LWYpxOaLOZoUOyTaUXwCEag0vVuKpWCU3CKhXk4gMH5KZAWCVItZGX8BIlzXJcEh4dCsN2uVD7GLf9cyIaBWF5dgRLQ8Co9Gw5QjKnOj37K7MgVb5QbeTneEV0fEx1Kyh2h0pjQUNB3hMpjQtfna3XlBtaQj3T+NGO2luHOruvZtZRdy2fZSRMI5wTrukNaVGkF9XWsysVVEoaQJlR2cKZz+saRsZaE3CI+fvZl/BvJ6Kd7wTDHUJVjfM3UeOkdjDLp6MygOmeHVEy/3TkSNELZzvZw4Dw3lBRy3X57J/t7zUB2YmiMjFRtDnsNbN1qwP3JlM3DyJaguxBy5lPNr/4IS+D197+5+t1v3/7yxdXLn7/5+pvX//rOnEyanQek/wUJmMIxjnxQVeZBbsTngj2Y4kXd3zdwk/snBNB0EkPBPQcX881uAou4AYgslExy8x6oZifR5uZvBp08fZndOaizLo7ZSQ++3i04gQMDk2mMfuebh9KY7urK/wBysel9')))
  File "<string>", line 98, in <module>
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mkdir -p /libx32/295isO/models/Lora'`

**Comment by 01Evin** [comment]
![image](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/129361256/b4bb5e35-7c7d-484e-a5fd-5d1636f1358f)

**Comment by 01Evin** [comment]
> ![image](https://user-images.githubusercontent.com/129361256/268484065-b4bb5e35-7c7d-484e-a5fd-5d1636f1358f.png)
大佬，加载云盘模型会有错误，只有插件vae和embedding加载了；还有方便提供未加密前的代码吗，比如我想改个最新的版本号，或者在选项中添加?最新版速度优化还是不错的

**Comment by newzf** [comment]
大佬：是又不行了吧，右上角的主机状态总是【正在连接】状态。

**Comment by 01Evin** [comment]
> 大佬：是又不行了吧，右上角的主机状态总是【正在连接】状态
可以用呀，网络问题吧？

**Comment by YRCFCIEWF** [comment]
> ![image](https://user-images.githubusercontent.com/129361256/268484065-b4bb5e35-7c7d-484e-a5fd-5d1636f1358f.png)

我只能加载插件，其余一概不行

**Comment by YRCFCIEWF** [comment]
顺便一提可以加个启动参数自定义的功能吗？

**Comment by GENTTAS** [comment]
dalao发现一个问题.

在使用最新版的时候

使用5.8G模型AbyssOrangeMix2_hard.safetensors

开启分层控制

开启[Lineart]  [Depth]  [Tile/Blur]  同时使用3个的情况下

会出现 Killed. 最后的单元格会自动结束,类似与崩溃一样  
2023-09-17 10:07:49,321 - ControlNet - INFO - controlnet_default_config
Killed

第一次出现killed,是开了2个半小时后RAM:12.68/12.68满载了 跑不出去图.随后killed.再次运行后使用相同的3模型+分层控制一样会出现 killed. 

随后去试了试9月14号的版本. 用的PRO号, 完全一样启动项设置 不开启高RAM T4GPU,相同数量的设置和模型 都是12.68.不开启
ngrok.

启动项默认为：--share --lowram  --disable-safe-unpickle  --disable-console-progressbars --xformers --enable-insecure-extension-access  --opt-sub-quad-attention --opt-channelslast --api"

试了半个小时也没有出现Killed.

**Comment by GENTTAS** [comment]
....rror
9 分 9 秒
完成时间：13:04 又不行了

**Comment by 01Evin** [comment]
我觉得是不是把项目安装在colab上，都会被检测？要是直接把目录装进云盘呢？我用大佬的框架改成comfy的直接挂云盘，一直挺稳，不会断线，或者是平台对comfy没那么严格

**Comment by GENTTAS** [comment]
感觉应该是.

**Comment by 01Evin** [comment]
刚才试了下，安装在云盘没事，目前还是很稳，用大佬的方法还不用给脚本加密，直接写在PY文件里面，再运行久一些试试

**Comment by 01Evin** [comment]
用colab还是建议扩容的，200G二十几块也不贵，也当支持下谷歌；
加载云盘的文件是慢了一点，我150G的模型和其他也要20分钟，错误我倒没碰到，顶多就是安装或启动时缺这缺哪，自己找到问题添加到脚本补回来就可以，自定义的话可以自定义设置吧，设置选项不会被覆盖，跟本地差不多了，之前camenduru大佬写的也有这种云盘版，后面我就是嫌加载慢不用了；
我习惯插件和模型的下载和更新新建一个笔记运行，这样可以不用连接GPU，省下免费时间，主笔记负责安装和启动就好；
自己是代码小白，看了挺多网上的脚本终于能理解一些，大佬的脚本也让我学习很多

**Comment by 01Evin** [comment]
![fa7fe5519f15ba9c5e8d40261ced478](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/129361256/128bdcd7-47dc-43ed-bd90-f022b2f242d2)
![2f2752c043fe062929a9dce96be9bf5](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/129361256/77d3bd79-9875-4594-845f-c982ee10e1bd)
单启动的话还是挺快的，10分钟左右

**Comment by newzf** [comment]
楼上兄弟能分享下脚本吗？

**Comment by 01Evin** [comment]
> 用colab还是建议扩容的，200G二十几块也不贵，也当支持下谷歌； 加载云盘的文件是慢了一点，错误我倒没碰到，顶多就是安装或启动时缺这缺哪，自己找到问题添加到脚本补回来就可以，自定义的话可以自定义设置吧，设置选项不会被覆盖，跟本地差不多了，之前camenduru大佬写的也有这种云盘版，后面我就是嫌加载慢不用了； 我习惯插件和模型的下载和更新新建一个笔记运行，这样可以不用连接GPU，省下免费时间，主笔记负责安装和启动就好； 自己是代码小白，看了挺多网上的脚本终于能理解一些，大佬的脚本也让我学习很多

确实有些插件报错，还是不太行，我再找找原因，emmm

**Comment by newzf** [comment]
> > > 用colab还是扩建议容量的，200G二十几块也贵，也当支持下谷歌；加载云盘的文件慢了一点，错误我倒没足，顶多就是安装或启动时缺这缺哪，自己找到问题添加脚本到补回来就可以了，自定义的话可以自定义设置吧，设置选项不会被覆盖，跟本地差不多了，之前camenduru大佬写的也有这种云盘版，后面我就是讨厌加载慢不用了；我习惯插件和模型的下载和更新新建一个笔记运行，这样可以不用连接GPU，省下免费时间，主笔记负责安装和启动就好；自己是代码小白，看了挺多网上的脚本终于能理解一些，大佬的脚本也让我学到很多
> > 
> > 
> > 确实有些插件报错，还是不太行，我再找原因，emmm
> 
> 需要一些插件依赖，我记得有整合过的秋叶包大概60多G吧不开谷歌云盘会员绝对是塞不下去。除非可以用其他网盘搭线过去。 https://pan.quark [. cn/s/1168b447a44e#/list/share/dde269bd2312404b8f3530e8afdf8e74-AI免费资源整理](https://pan.quark.cn/s/1168b447a44e#/list/share/dde269bd2312404b8f3530e8afdf8e74-AI%E5%85%8D%E8%B4%B9%E8%B5%84%E6%BA%90%E6%95%B4%E7%90%86) https://www.123pan.com/s/Js43jv-eHPJ.html
> 
> 但是也能用就是了我现在草莓倒是默认的插件全部都用外加的 openpose editor 和 adetailer 也可以用 其他转绘插件现在还没试估计不太行。

麻烦说下提取码

**Comment by Van-wise** [comment]
> 用colab还是建议扩容的，200G二十几块也不贵，也当支持下谷歌； 加载云盘的文件是慢了一点，错误我倒没碰到，顶多就是安装或启动时缺这缺哪，自己找到问题添加到脚本补回来就可以，自定义的话可以自定义设置吧，设置选项不会被覆盖，跟本地差不多了，之前camenduru大佬写的也有这种云盘版，后面我就是嫌加载慢不用了； 我习惯插件和模型的下载和更新新建一个笔记运行，这样可以不用连接GPU，省下免费时间，主笔记负责安装和启动就好； 自己是代码小白，看了挺多网上的脚本终于能理解一些，大佬的脚本也让我学习很多

有靠谱的云盘扩容渠道吗

**Comment by GENTTAS** [comment]
> > > > 用colab还是扩建议容量的，200G二十几块也贵，也当支持下谷歌；加载云盘的文件慢了一点，错误我倒没足，顶多就是安装或启动时缺这缺哪，自己找到问题添加脚本到补回来就可以了，自定义的话可以自定义设置吧，设置选项不会被覆盖，跟本地差不多了，之前camenduru大佬写的也有这种云盘版，后面我就是讨厌加载慢不用了；我习惯插件和模型的下载和更新新建一个笔记运行，这样可以不用连接GPU，省下免费时间，主笔记负责安装和启动就好；自己是代码小白，看了挺多网上的脚本终于能理解一些，大佬的脚本也让我学到很多
> > > 
> > > 
> > > 确实有些插件报错，还是不太行，我再找原因，emmm
> > 
> > 
> > 需要一些插件依赖，我记得有整合过的秋叶包大概60多G吧不开谷歌云盘会员绝对是塞不下去。除非可以用其他网盘搭线过去。 https://pan.quark [. cn/s/1168b447a44e#/list/share/dde269bd2312404b8f3530e8afdf8e74-AI免费资源整理](https://pan.quark.cn/s/1168b447a44e#/list/share/dde269bd2312404b8f3530e8afdf8e74-AI%E5%85%8D%E8%B4%B9%E8%B5%84%E6%BA%90%E6%95%B4%E7%90%86) https://www.123pan.com/s/Js43jv-eHPJ.html
> > 但是也能用就是了我现在草莓倒是默认的插件全部都用外加的 openpose editor 和 adetailer 也可以用 其他转绘插件现在还没试估计不太行。
> 
> 麻烦说下提取码

https://www.123pan.com/s/Js43jv-eHPJ.html 提取码:QYtw

**Comment by 01Evin** [comment]
> > 用colab还是建议扩容的，200G二十几块也不贵，也当支持下谷歌； 加载云盘的文件是慢了一点，错误我倒没碰到，顶多就是安装或启动时缺这缺哪，自己找到问题添加到脚本补回来就可以，自定义的话可以自定义设置吧，设置选项不会被覆盖，跟本地差不多了，之前camenduru大佬写的也有这种云盘版，后面我就是嫌加载慢不用了； 我习惯插件和模型的下载和更新新建一个笔记运行，这样可以不用连接GPU，省下免费时间，主笔记负责安装和启动就好； 自己是代码小白，看了挺多网上的脚本终于能理解一些，大佬的脚本也让我学习很多
> 
> 有靠谱的云盘扩容渠道吗

tb搜colab就会有扩容业务的，便宜的21，贵的30

**Comment by s4afa451dgf415f** [comment]
之前听说过整个项目放云盘运行的，感觉挺抽象，有扫盘的说法。

**Comment by s4afa451dgf415f** [comment]
> 顺便一提可以加个启动参数自定义的功能吗？想自己添加修改参数

加了，你自己加

**Comment by s4afa451dgf415f** [comment]
这楼太乱了懒得看，以后有bug发个新问题
