### ISSUE TITLE
.

### ISSUE THREAD

**Issue by GENTTAS** [s4afa451dgf415f/colab_stable_diffusion#27]
.

**Comment by 01Evin** [comment]
![微信截图_20230921095551](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/129361256/c6bdeee5-f65b-4313-bea3-093ed60d4cb3)
就是彻底没戏了

**Comment by GENTTAS** [comment]
> ![微信截图_20230921095551](https://user-images.githubusercontent.com/129361256/269461265-c6bdeee5-f65b-4313-bea3-093ed60d4cb3.png) 就是彻底没戏了

你是加密的运行方式 也弹这个么？我是用9月14号的弹出来的。没用dalao的加密。 除非他是检测运行后的代码那确实没戏。那只能续pro 或者换平台了

**Comment by 01Evin** [comment]
大佬最新的版本好像不会弹出这个

**Comment by Benson80** [comment]
运行几分钟后就不行了，现在这么不稳定吗？

**Comment by GENTTAS** [comment]
> emmm....刚刚用大佬最新的脚本运行成功几分钟后也出现了这个警告，应该是怎么加密都没用了

那就是运行后被检测了,

**Comment by GENTTAS** [comment]
> emmm....刚刚用大佬最新的脚本运行成功几分钟后也出现了这个警告，应该是怎么加密都没用了

我找到了解决办法,但是由于没办法改dalao的目录现在还测试不了.加密搞的头皮发麻。或许可以用9月14号的

**Comment by 01Evin** [comment]
> > emmm....刚刚用大佬最新的脚本运行成功几分钟后也出现了这个警告，应该是怎么加密都没用了
> 
> 我找到了解决办法,但是由于没办法改dalao的目录现在还测试不了.加密搞的头皮发麻。或许可以用9月14号的

什么思路？我也试试

**Comment by GENTTAS** [comment]
> > > emmm....刚刚用大佬最新的脚本运行成功几分钟后也出现了这个警告，应该是怎么加密都没用了
> > 
> > 
> > 我找到了解决办法,但是由于没办法改dalao的目录现在还测试不了.加密搞的头皮发麻。或许可以用9月14号的
> 
> 什么思路？我也试试

把运行时 隐藏 放在文件里 在把文件移植到 云盘里

**Comment by GENTTAS** [comment]
> 你将文件放在云盘，最终还是要关联到colab，那边还是会获取你的云盘文件夹和文件，依然会检测得到。所以现在还是不确定这次检测的机制什么，之前是检测文件夹关键词，stable diffusion，webui，还有模型后缀。这次还不确定，但愿不是检测运行后的输出代码。

就是运行后的输出代码

**Comment by GENTTAS** [comment]
现在就是求dalao放一下 加密前的PY文件

**Comment by GENTTAS** [comment]
![Image text](https://thumbnail1.baidupcs.com/thumbnail/00b74c86cif879b7d95a634634947bca?fid=1562992632-250528-79993909431015&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-c7yTETB9Kp2OYmI%2fespmaT79sKI%3d&expires=8h&chkbd=0&chkv=0&dp-logid=351381899928235536&dp-callid=0&time=1695283200&size=c1600_u900&quality=90&vuk=1562992632&ft=image&autopolicy=1)

**Comment by GENTTAS** [comment]
![Image text](https://thumbnail1.baidupcs.com/thumbnail/00b74c86cif879b7d95a634634947bca?fid=1562992632-250528-79993909431015&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-c7yTETB9Kp2OYmI%2fespmaT79sKI%3d&expires=8h&chkbd=0&chkv=0&dp-logid=351381899928235536&dp-callid=0&time=1695283200&size=c1600_u900&quality=90&vuk=1562992632&ft=image&autopolicy=1

**Comment by 01Evin** [comment]
运行了多久？我上午也能打开的，就是过一会会被检测

**Comment by GENTTAS** [comment]
> 运行了多久？我上午也能打开的，就是过一会会被检测

吃完回来了 开到了现在 顺便清了一下手游日常

**Comment by GENTTAS** [comment]
> 运行了多久？我上午也能打开的，就是过一会会被检测

![Image text](https://thumbnail1.baidupcs.com/thumbnail/03bab4260i05a899efd1885781361bd4?fid=1562992632-250528-820159873357957&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-RIlEQuOZ1d6if67X2GZGoRknZy8%3d&expires=8h&chkbd=0&chkv=0&dp-logid=353704668752998676&dp-callid=0&time=1695294000&size=c1600_u900&quality=90&vuk=1562992632&ft=image&autopolicy=1)

自带的插件基本都可以：高修也用了

没有测试插件就是分层控制 还有IP A

第一次运行了45分钟,我准备去装插件。

然后发现了致命的缺陷 当你装完插件你在打开的时候 没有任何链接。 卡在了加载模型外加的模型。

而且第一次我明明启用了 ngk 的网络加速 却没有链接。也就是说你可以第一次运行,但是你想装插件后再次运行 虽然单元格一直在运行 但是没有链接了。 实测了下了很稳 没有断开。 基本确定了 就是检测的是运行中的代码。 还有装插件前没有截图 重新断开了。 等会在过1个小时在截个图吧。

**Comment by wage666** [comment]
> > 运行了多长时间？我上午也能打开的，就是过一会会被检测到
> 
> ![图片文字](https://camo.githubusercontent.com/66746d4359b520a133e478be54690ee84a1b84ffe0128842343490cf14d1fd95/68747470733a2f2f7468756d626e61696c312e62616964757063732e636f6d2f7468756d626e61696c2f30336261623432363069303561383939656664313838353738313336316264343f6669643d313536323939323633322d3235303532382d3832303135393837333335373935372672743d7072267369676e3d4644544145522d44436237343063636335353131653565386665646366663036623038313230332d52496c4551754f5a316436696636375832475a476f526b6e5a793825336426657870697265733d38682663686b62643d302663686b763d302664702d6c6f6769643d3335333730343636383735323939383637362664702d63616c6c69643d302674696d653d313639353239343030302673697a653d63313630305f75393030267175616c6974793d39302676756b3d313536323939323633322666743d696d616765266175746f706f6c6963793d31)
> 
> 自带的插件基本都可以：高修也用了
> 
> 没有测试插件就是分层控制还有IP A
> 
> 第一次运行了 45 分钟，我准备去安装插件。
> 
> 然后当你安装完插件时发现致命的缺陷，你在打开的时候没有任何链接。卡在了加载模型外加的模型。
> 
> 第一次而且我显然实现了 ngk 的网络加速却没有链接。既然你可以第一次运行，但是你想装插件之后再次运行不会。给你链接。虽然单元格一直在运行但是没有 链接了。实测了很稳定没有中断。基本确定了就是检测运行中的代码。还有装插件前没有截图重新中断了。等会在过1个小时在截个图吧。

你是个天才，不，你是个英雄，期待你的最终作品

**Comment by GENTTAS** [comment]
![Image text](https://thumbnail1.baidupcs.com/thumbnail/fa91ffdb6k81ee616d758e6ce1e23278?fid=1562992632-250528-13431591415427&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-ZfEBPE7dL5sT0ZH8e1ZG9OYriZs%3d&expires=8h&chkbd=0&chkv=0&dp-logid=354548208095255504&dp-callid=0&time=1695297600&size=c1600_u900&quality=90&vuk=1562992632&ft=image&autopolicy=1) ,基本没问题。就是看dalao更新一下negrok不显示的问题了。把加载模型放到最后面 还有没有加密的CY文件
