### ISSUE TITLE
关于drive共用问题

### ISSUE THREAD

**Issue by Li1177** [s4afa451dgf415f/colab_stable_diffusion#3]
看到作者的一句话：弄几个号在云盘里主号的json给其他号添加编辑权限就实现了所有号共用
我一直想实现的就是，一个主drive 100g，然后别的几个谷歌账号的colab都可以使用这个drive，
想问下具体该怎么实现啊？ 就是别的账号的colab启动webui的时候， 怎样才开始挂载主账号的
drive 硬盘啊？

**Comment by s4afa451dgf415f** [comment]
原理大概就是model.json文件用来记录需要下载的mod信息，每次部署他都会自动去下载需要的模型文件，我主号的model.json共享给其他小号并且让小号也拥有编辑权限就实现共用，重点就是同步了这个文件，而不是小号挂载主号云盘。你不懂就跟着视频的步骤去做就行了。

**Comment by Li1177** [comment]
在哪里有视频啊？

**Comment by Van-wise** [comment]
> 在哪里有视频啊？

https://www.bilibili.com/video/BV17h4y1J79g/

**Comment by s4afa451dgf415f** [comment]
没问题了麻烦问题关一下，谢了。
