### ISSUE TITLE
如果弹出警告中断你的连接，建议不要继续尝试

### ISSUE THREAD

**Issue by 01Evin** [s4afa451dgf415f/colab_stable_diffusion#31]
![image](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/129361256/2b0f7ada-5909-4d62-b5f4-3dd88d2b3d2e)
前几天被封过一次，第二次就不给我申诉了

**Comment by GHIUJH** [comment]
他们加大了封号的力度,大概是24号的时候第一次被封就不可以申诉了。我3个号 里面2个号续过PRO会员。都弹出过中断链接。唯独那个小号被永封了。 不过你可以试试缴费PRO会员 账号是否可以解封。

**Comment by 01Evin** [comment]
第一次收到申诉大概两天后解封，现在只能继续跟他拉扯了，不过还有六个号，问题不大，就是主号用的时间挺久了
