### ISSUE TITLE
用不了xl lora模型

### ISSUE THREAD

**Issue by walekr12** [s4afa451dgf415f/colab_stable_diffusion#43]
sdxl不用xl lora可以正常生成图片，如果用了的话生成图片会在95%-100%的时候出现连接错误（connect error），应该怎么办呀?

**Comment by s4afa451dgf415f** [comment]
sdxl只支持xl的lora

**Comment by walekr12** [comment]
是用的xl lora，尝试多次最后都会连接错误

**Comment by s4afa451dgf415f** [comment]
12G内存太小爆了，我改了下参数。如果之后爆显存用tiledVAE这个插件

**Comment by walekr12** [comment]
谢谢大佬，没问题了
