### ISSUE TITLE
[BUG]無法運行webui

### ISSUE THREAD

**Issue by Cosplayeridol** [s4afa451dgf415f/colab_stable_diffusion#46]
/content/stable-diffusion-webui
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing clip
Installing open_clip
Cloning Stable Diffusion into /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
Cloning into '/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai'...
remote: Enumerating objects: 580, done.
remote: Counting objects: 100% (357/357), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 580 (delta 260), reused 231 (delta 231), pack-reused 223
Receiving objects: 100% (580/580), 73.44 MiB | 15.68 MiB/s, done.
Resolving deltas: 100% (279/279), done.
Cloning Stable Diffusion XL into /content/stable-diffusion-webui/repositories/generative-models...
Cloning into '/content/stable-diffusion-webui/repositories/generative-models'...
remote: Enumerating objects: 941, done.
remote: Total 941 (delta 0), reused 0 (delta 0), pack-reused 941
Receiving objects: 100% (941/941), 43.85 MiB | 16.05 MiB/s, done.
Resolving deltas: 100% (491/491), done.
Cloning K-diffusion into /content/stable-diffusion-webui/repositories/k-diffusion...
Cloning into '/content/stable-diffusion-webui/repositories/k-diffusion'...
remote: Enumerating objects: 1340, done.
remote: Counting objects: 100% (622/622), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 1340 (delta 576), reused 547 (delta 536), pack-reused 718
Receiving objects: 100% (1340/1340), 242.04 KiB | 18.62 MiB/s, done.
Resolving deltas: 100% (939/939), done.
Cloning CodeFormer into /content/stable-diffusion-webui/repositories/CodeFormer...
Cloning into '/content/stable-diffusion-webui/repositories/CodeFormer'...
remote: Enumerating objects: 594, done.
remote: Counting objects: 100% (594/594), done.
remote: Compressing objects: 100% (316/316), done.
remote: Total 594 (delta 287), reused 493 (delta 269), pack-reused 0
Receiving objects: 100% (594/594), 17.31 MiB | 16.61 MiB/s, done.
Resolving deltas: 100% (287/287), done.
Cloning BLIP into /content/stable-diffusion-webui/repositories/BLIP...
Cloning into '/content/stable-diffusion-webui/repositories/BLIP'...
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 277 (delta 137), reused 136 (delta 135), pack-reused 112
Receiving objects: 100% (277/277), 7.03 MiB | 20.18 MiB/s, done.
Resolving deltas: 100% (152/152), done.
Installing requirements for CodeFormer
Installing requirements
Downloading pose_landmark_full.tflite...
Downloading pose_web.binarypb...
Downloading pose_solution_packed_assets.data...
Downloading pose_solution_simd_wasm_bin.wasm...
Downloading pose_solution_packed_assets_loader.js...
Downloading pose_solution_simd_wasm_bin.js...
Installing sd-webui-controlnet requirement: fvcore
Installing sd-webui-controlnet requirement: mediapipe
Installing sd-webui-controlnet requirement: onnxruntime
Installing sd-webui-controlnet requirement: svglib
ControlNet init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Installing sd-webui-controlnet requirement: handrefinerportable
Installing sd-webui-controlnet requirement: depth_anything
Installing sd-webui-prompt-all-in-one: execjs
Installing sd-webui-prompt-all-in-one: pathos
Installing sd-webui-prompt-all-in-one: openai
Installing sd-webui-prompt-all-in-one: boto3
Installing sd-webui-prompt-all-in-one: aliyunsdkcore
Installing sd-webui-prompt-all-in-one: aliyunsdkalimt
loading WD14-tagger reqs from /content/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/requirements.txt
Checking WD14-tagger requirements.
Launching Web UI with arguments: --share --medvram-sdxl --disable-safe-unpickle --disable-console-progressbars --xformers --enable-insecure-extension-access --opt-sub-quad-attention --no-half-vae --opt-channelslast --api --theme=light
WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.2.1+cu121)
    Python  3.10.13 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
*** Error setting up CodeFormer
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/codeformer_model.py", line 30, in setup_model
        from modules.codeformer.codeformer_arch import CodeFormer
      File "/content/stable-diffusion-webui/modules/codeformer/codeformer_arch.py", line 9, in <module>
        from modules.codeformer.vqgan_arch import VQAutoEncoder, ResBlock
      File "/content/stable-diffusion-webui/modules/codeformer/vqgan_arch.py", line 11, in <module>
        from basicsr.utils import get_root_logger
      File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
        from .data import *
      File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
        _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
      File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
        _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
        from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
      File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
        from torchvision.transforms.functional_tensor import rgb_to_grayscale
    ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

---
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/content/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/content/stable-diffusion-webui/modules/launch_utils.py", line 436, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 52, in webui
    initialize.initialize()
  File "/content/stable-diffusion-webui/modules/initialize.py", line 71, in initialize
    from modules import gfpgan_model
  File "/content/stable-diffusion-webui/modules/gfpgan_model.py", line 4, in <module>
    import gfpgan
  File "/usr/local/lib/python3.10/dist-packages/gfpgan/__init__.py", line 3, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/gfpgan/data/__init__.py", line 10, in <module>
    _dataset_modules = [importlib.import_module(f'gfpgan.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/local/lib/python3.10/dist-packages/gfpgan/data/__init__.py", line 10, in <listcomp>
    _dataset_modules = [importlib.import_module(f'gfpgan.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/gfpgan/data/ffhq_degradation_dataset.py", line 7, in <module>
    from basicsr.data import degradations as degradations
  File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

**Comment by s4afa451dgf415f** [comment]
Google updated Torch's version, which led to Xformers not being compatible with the corresponding version of SD. Currently, I can only reinstall Torch, which will take an extra 1-2 minutes. I will look for a solution afterwards

**Comment by Cosplayeridol** [comment]
> Google updated Torch's version, which led to Xformers not being compatible with the corresponding version of SD. Currently, I can only reinstall Torch, which will take an extra 1-2 minutes. I will look for a solution afterwards

The webui still cannot be used. The prompt in step 4 includes, for example, the file path of lora, which is missing. The situation seems to be getting worse.

**Comment by s4afa451dgf415f** [comment]
![image](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/90437738/345b3589-8651-4bda-b30e-3229be28c9ff)
I tested it locally and it ran fine, generating the corresponding images. If you still encounter issues after updating from Git, i need your printed error log to analyze.

**Comment by Cosplayeridol** [comment]
> ![image](https://private-user-images.githubusercontent.com/90437738/316513577-345b3589-8651-4bda-b30e-3229be28c9ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDQ5MjQsIm5iZiI6MTcxMTQ0NDYyNCwicGF0aCI6Ii85MDQzNzczOC8zMTY1MTM1NzctMzQ1YjM1ODktODY1MS00YmRhLWIzMGUtMzIyOWJlMjhjOWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA5MTcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OTNmMjQ4OGZiMDZlZmMxZTllYmFjOTg4MjY0N2IxNTA0ZjdkYzdlMDcxMjVkM2I1ZTZjMzc5ZjFkMDQ0NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bU_kOqcpBaxUL8WAUqfjC5MshtLIq7ite-mTyWQWRUs) I tested it locally and it ran fine, generating the corresponding images. If you still encounter issues after updating from Git, i need your printed error log to analyze.

Unable to download model
2.2 step
[{'name': 'fantasticmix25d', 'type': '', 'downloadLink': 'https://civitai.com/models/20632/fantasticmix25d', 'size': '', 'path': '/content/stable-diffusion-webui/models/Lora', 'lastChangeDate': '2024-03-24'}, {'name': 'fantasticmix25d', 'type': '', 'downloadLink': 'https://civitai.com/models/20632/fantasticmix25d', 'size': '', 'path': '/content/stable-diffusion-webui/models/Lora', 'lastChangeDate': '2024-03-26'}, {'name': 'fantasticmix2.5D.5D', 'type': '', 'downloadLink': 'https://civitai.com/models/20632?modelVersionId=143050', 'size': '5.78GB', 'path': '/content/stable-diffusion-webui/models/Stable-diffusion', 'lastChangeDate': '2024-03-26'}, {'name': 'mordred-fateapocrypha-lora-or-6-outfits', 'type': '', 'downloadLink': 'https://civitai.com/models/342287/mordred-fateapocrypha-lora-or-6-outfits', 'size': '', 'path': '/content/stable-diffusion-webui/models/Lora', 'lastChangeDate': '2024-03-26'}]
[{'name': 'fantasticmix2.5D', 'type': '', 'downloadLink': 'https://civitai.com/models/20632/fantasticmix25d', 'size': '', 'path': '/content/stable-diffusion-webui/models/Stable-diffusion', 'lastChangeDate': '2024-03-26'}]
/content/stable-diffusion-webui/models/Lora/fantasticmix25d不存在，重命名失败
new 1 0
old 1 3
fantasticmix25d为旧不重复mod，将删除
fantasticmix25d不存在，删除失败
fantasticmix2.5D.5D为旧不重复mod，将删除
fantasticmix2.5D.5D不存在，删除失败
mordred-fateapocrypha-lora-or-6-outfits为旧不重复mod，将删除
mordred-fateapocrypha-lora-or-6-outfits不存在，删除失败
[]
![image](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/85826393/e2405516-c8a0-458d-ad27-678c503e3f53)

**Comment by Cosplayeridol** [comment]
> > ![image](https://private-user-images.githubusercontent.com/90437738/316513577-345b3589-8651-4bda-b30e-3229be28c9ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDQ5MjQsIm5iZiI6MTcxMTQ0NDYyNCwicGF0aCI6Ii85MDQzNzczOC8zMTY1MTM1NzctMzQ1YjM1ODktODY1MS00YmRhLWIzMGUtMzIyOWJlMjhjOWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA5MTcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OTNmMjQ4OGZiMDZlZmMxZTllYmFjOTg4MjY0N2IxNTA0ZjdkYzdlMDcxMjVkM2I1ZTZjMzc5ZjFkMDQ0NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bU_kOqcpBaxUL8WAUqfjC5MshtLIq7ite-mTyWQWRUs) I tested it locally and it ran fine, generating the corresponding images. If you still encounter issues after updating from Git, i need your printed error log to analyze.
> 
> Unable to download model 2.2 step [{'name': 'fantasticmix25d', 'type': '', 'downloadLink': 'https://civitai.com/models/20632/fantasticmix25d', 'size': '', 'path': '/content/stable-diffusion-webui/models/Lora', 'lastChangeDate': '2024-03-24'}, {'name': 'fantasticmix25d', 'type': '', 'downloadLink': 'https://civitai.com/models/20632/fantasticmix25d', 'size': '', 'path': '/content/stable-diffusion-webui/models/Lora', 'lastChangeDate': '2024-03-26'}, {'name': 'fantasticmix2.5D.5D', 'type': '', 'downloadLink': 'https://civitai.com/models/20632?modelVersionId=143050', 'size': '5.78GB', 'path': '/content/stable-diffusion-webui/models/Stable-diffusion', 'lastChangeDate': '2024-03-26'}, {'name': 'mordred-fateapocrypha-lora-or-6-outfits', 'type': '', 'downloadLink': 'https://civitai.com/models/342287/mordred-fateapocrypha-lora-or-6-outfits', 'size': '', 'path': '/content/stable-diffusion-webui/models/Lora', 'lastChangeDate': '2024-03-26'}] [{'name': 'fantasticmix2.5D', 'type': '', 'downloadLink': 'https://civitai.com/models/20632/fantasticmix25d', 'size': '', 'path': '/content/stable-diffusion-webui/models/Stable-diffusion', 'lastChangeDate': '2024-03-26'}] /content/stable-diffusion-webui/models/Lora/fantasticmix25d不存在，重命名失败 new 1 0 old 1 3 fantasticmix25d为旧不重复mod，将删除 fantasticmix25d不存在，删除失败 fantasticmix2.5D.5D为旧不重复mod，将删除 fantasticmix2.5D.5D不存在，删除失败 mordred-fateapocrypha-lora-or-6-outfits为旧不重复mod，将删除 mordred-fateapocrypha-lora-or-6-outfits不存在，删除失败 [] ![image](https://private-user-images.githubusercontent.com/85826393/316800064-e2405516-c8a0-458d-ad27-678c503e3f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDY5ODcsIm5iZiI6MTcxMTQ0NjY4NywicGF0aCI6Ii84NTgyNjM5My8zMTY4MDAwNjQtZTI0MDU1MTYtYzhhMC00NThkLWFkMjctNjc4YzUwM2UzZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA5NTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYjUxYTJkOTIxMmY2MDRmZGNkYjA4MTEzZmRiMWNhMWVlNDlhMmQ2Y2VjODQxMTg5YTY5MDcwNWZmZGJiYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ohi9OlMlqaHU4kE0ehYKuEYGbeZqQcKSboISucyYb_o)

I tried it again, and the downloaded model file was only 311kb, but the total size of this model was 5.78GB. Not only the CHECKPOINT model, but also the lora model is like this. The complete file cannot be downloaded, and the file size is only between 100~400kb.

**Comment by s4afa451dgf415f** [comment]
![QQ截图20240326193414](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/90437738/66fb980f-3a38-4b7e-908d-ab374b8eedf6)
In fact, the link you copied is the webpage address of the model, but what's needed here is the download address, as shown in the picture to be correct.And the download paths for the model's files and checkpoints are not necessary as they will automatically be placed in the specified path unless you need to download something else like embedding and then you will need to fill in the path.
