### ISSUE TITLE
［BUG］一些SDXL模型無法下載成功

### ISSUE THREAD

**Issue by Cosplayeridol** [s4afa451dgf415f/colab_stable_diffusion#47]
Some Checkpoint and Lora models on the civitai website cannot be downloaded, and an error message will appear.  I feel that the errors reported are all sdxl models. If you need the program code, I will provide it later.

Note: During my use yesterday, I also encountered the problem that the lora model of sdxl could not be displayed in the webui by uploading it myself (I bypassed the download method).

**Comment by s4afa451dgf415f** [comment]
If the file you downloaded is not a model but displays a webpage instead, then you need to input the Cookie,The specific tutorial code is included, but it probably didn't pop up due to an error caused by updates to civitai rendering it ineffective.

**Comment by Cosplayeridol** [comment]
This is very useful. Through testing, I can perfectly download any model that cannot be downloaded by adding ?token=(API key) after the url, or changing ?type=Model*** to ?token=(API key). This is not a BUG of this colab project. I have never used the API function before. Thank you for the reminder.❤️
