### ISSUE TITLE
[ERROR]無法新增mod

### ISSUE THREAD

**Issue by Cosplayeridol** [s4afa451dgf415f/colab_stable_diffusion#48]
Add checkpoint download link, showing 'DataFrame' object has no attribute 'append'

There haven't been any problems with this function before. I don't know what I did wrong to prevent the new mod from being added. Maybe you can easily reproduce this error.

![image](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/85826393/8cd4d42a-dda7-4da9-98ff-19b63f13f30a)

**Comment by s4afa451dgf415f** [comment]
fixed
