### ISSUE TITLE
[Question]關於自行升級webui版本的問題

### ISSUE THREAD

**Issue by Cosplayeridol** [s4afa451dgf415f/colab_stable_diffusion#49]
I tried to change the version downloaded by webui in step 2.0 to the latest version 1.9.3
![image](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/85826393/43b32f7c-0e04-49b6-8938-21d4ec81b173)
But when doing step 4, I can't generate another URL, I can only get the URL http://127.0.0.1:7860 (I can't access this URL from the beginning, but keep using another URL)
![image](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/85826393/abb224a4-f2ea-47a0-a4d9-2cae93fb9ff6)
I don't know what I missed, so I can only generate one URL, or will it cause unknown errors in the project if I simply modify the webui download version in step 2.0?

**Comment by Cosplayeridol** [comment]
When I enter webui through ngrok, this prompt appears
![image](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/85826393/84ca9b61-4d6d-49d2-97de-3b8ab071aaf3)
The version of webui has indeed changed to the latest version 1.9.3
![image](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/85826393/76934be3-4ae4-4995-8848-2ac1c98856dc)
The image can be generated, but the webui does not show the progress bar
![image](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/85826393/f4b31a7f-9434-45bb-b1c0-b08a4ea23080)
I haven't tested other functions, so I don't know if upgrading the webui version in this way will cause other unknown errors.

**Comment by ASDASDAS32** [comment]
This has nothing to do with 1.9.3, I've been using 1.9.3 since it was first updated. And just today the remote share link disappeared.
It's either a colab problem or a gradio problem.
Now it still works with other remotes. But there are a lot of bugs. Just use the other remote for now.
Fuck Google for torturing users!

**Comment by Cosplayeridol** [comment]
> This has nothing to do with 1.9.3, I've been using 1.9.3 since it was first updated. And just today the remote share link disappeared. It's either a colab problem or a gradio problem. Now it still works with other remotes. But there are a lot of bugs. Just use the other remote for now. Fuck Google for torturing users!

If this is really the case, how to solve the problem of failed access to http://127.0.0.1:7860? Can you successfully access this URL after running the project?

**Comment by ASDASDAS32** [comment]
> > 这与 1.9.3 无关，自从 1.9.3 第一次更新以来我一直在使用它。就在今天，远程共享链接消失了。这要么是一个colab问题，要么是一个gradio问题。现在它仍然可以与其他遥控器配合使用。但也有很多bug。现在只需使用另一个遥控器即可。去他妈的谷歌折磨用户！
> 
> 如果确实如此，如何解决访问http://127.0.0.1:7860失败的问题？项目运行后能否成功访问该URL？ 我现在只能通过ngrok访问webui，而且它的配额总是很容易耗尽。我必须申请多个帐户才能满足我的需要。

Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /usr/local/lib/python3.10/dist-packages/gradio

**Comment by ASDASDAS32** [comment]
> > 这与 1.9.3 无关，自从 1.9.3 第一次更新以来我一直在使用它。就在今天，远程共享链接消失了。这要么是一个colab问题，要么是一个gradio问题。现在它仍然可以与其他遥控器配合使用。但也有很多bug。现在只需使用另一个遥控器即可。去他妈的谷歌折磨用户！
> 
> 如果确实如此，如何解决访问http://127.0.0.1:7860失败的问题？项目运行后能否成功访问该URL？ 我现在只能通过ngrok访问webui，而且它的配额总是很容易耗尽。我必须申请多个帐户才能满足我的需要。



> > This has nothing to do with 1.9.3, I've been using 1.9.3 since it was first updated. And just today the remote share link disappeared. It's either a colab problem or a gradio problem. Now it still works with other remotes. But there are a lot of bugs. Just use the other remote for now. Fuck Google for torturing users!
> 
> If this is really the case, how to solve the problem of failed access to http://127.0.0.1:7860? Can you successfully access this URL after running the project? I can only access webui through ngrok now, and its quota is always exhausted easily. I have to apply for several accounts to meet my needs.

No solution for ngrok for the time being.

**Comment by Cosplayeridol** [comment]
> Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2.
> 
> Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps:
> 
> 1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
> 2. Rename the downloaded file to: frpc_linux_amd64_v0.2
> 3. Move the file to this location: /usr/local/lib/python3.10/dist-packages/gradio

I don't understand this. How do I do it on colab?
Do I need to download this file and put it into the colab file?

**Comment by ASDASDAS32** [comment]
> > Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2.
> > Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps:
> > 
> > 1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
> > 2. Rename the downloaded file to: frpc_linux_amd64_v0.2
> > 3. Move the file to this location: /usr/local/lib/python3.10/dist-packages/gradio
> 
> I don't understand this. How do I do it on colab? Do I need to download this file and put it into the colab file?

Colab may not have been missing such files before, but they seem to be missing today. I tried using this method. But it doesn't work.
This is the message that pops up occasionally when I start SD
Maybe someone will fix it, but for now the best thing to do is to register more ngrok accounts.

**Comment by miaowm5** [comment]
gradio down yesterday and seems fine now
https://github.com/lllyasviel/Fooocus/issues/2817
