### ISSUE TITLE
无法下载列表里新添加的模型

### ISSUE THREAD

**Issue by walekr12** [s4afa451dgf415f/colab_stable_diffusion#51]
![屏幕截图 2024-05-08 104925](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/161548283/d6d0f698-5a88-476a-927d-d59302e27625)

**Comment by walekr12** [comment]
![J1Y99)NDJA57K%VXXHCV9RN](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/161548283/5d0d343d-e435-4b70-9070-3f18fa8d5712)
![T@K$N71AXM1X%X75$~0BSF2](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/161548283/5d6b1dfc-b017-4c2f-b766-06b1928e6d29)
这个set cookie好像有两个，我两个都试了，都不起作用。然后请求表头和响应表头的set-cookie和cookie都试过了都不行，是哪里出错了？

**Comment by walekr12** [comment]
![S%D{`KH(~1@B9FJ~I@AT@4R](https://github.com/s4afa451dgf415f/colab_stable_diffusion/assets/161548283/a71c496d-052d-4bfd-9cdd-8b8c11882e67)
huggingface的也不行，不晓得是不是代码里边不能下载controlnet模型，但是我把链接地址放在前面第二步里面的代码里面就可以下载成功了。

**Comment by Cosplayeridol** [comment]
> ![J1Y99)NDJA57K%VXXHCV9RN](https://private-user-images.githubusercontent.com/161548283/329753214-5d0d343d-e435-4b70-9070-3f18fa8d5712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODE4MzIsIm5iZiI6MTcxNTU4MTUzMiwicGF0aCI6Ii8xNjE1NDgyODMvMzI5NzUzMjE0LTVkMGQzNDNkLWU0MzUtNGI3MC05MDcwLTNmMThmYThkNTcxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNjI1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjkxMjY2Njg1YWU0OGNkMzk4NWFkMzE1ZTZiZDFkOWQ2ZTgyYWY5ZDc3YzIxNWNjMjFkOGEyNmE5NWM0ZTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D2_UaFXPi5dG-IkC9yLdg8sv9qkyV2eTlZhu5bJrfs0) ![T@K$N71AXM1X%X75$~0BSF2](https://private-user-images.githubusercontent.com/161548283/329753217-5d6b1dfc-b017-4c2f-b766-06b1928e6d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODE4MzIsIm5iZiI6MTcxNTU4MTUzMiwicGF0aCI6Ii8xNjE1NDgyODMvMzI5NzUzMjE3LTVkNmIxZGZjLWIwMTctNGMyZi1iNzY2LTA2YjE5MjhlNmQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNjI1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODQzNjc0NzhiYWE4OTA1MWU2Njg0NDdhZTgwMDQ0YmMwODVkMGRjNDU3YTU3ZGUzYWIzMWE1NDJhNTNjZWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zaYNU9PhJGf2DIoaJf2g3EDW-47fgmQ_Jsync1wBLz0) 这个set cookie好像有两个，我两个都试了，都不起作用。然后请求表头和响应表头的set-cookie和cookie都试过了都不行，是哪里出错了？

The solution to the problem that the model cannot be downloaded is simply that some models on the civitai website have been set by the author to download only to logged-in users. You need to manually fill in the token of your account after the download link. You can use Google to learn how to apply for civitai users token.
▼this is the solution
https://github.com/s4afa451dgf415f/colab_stable_diffusion/issues/47#issuecomment-2053672958

**Comment by walekr12** [comment]
> > ![J1Y99)NDJA57K%VXXHCV9RN](https://private-user-images.githubusercontent.com/161548283/329753214-5d0d343d-e435-4b70-9070-3f18fa8d5712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODE4MzIsIm5iZiI6MTcxNTU4MTUzMiwicGF0aCI6Ii8xNjE1NDgyODMvMzI5NzUzMjE0LTVkMGQzNDNkLWU0MzUtNGI3MC05MDcwLTNmMThmYThkNTcxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNjI1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjkxMjY2Njg1YWU0OGNkMzk4NWFkMzE1ZTZiZDFkOWQ2ZTgyYWY5ZDc3YzIxNWNjMjFkOGEyNmE5NWM0ZTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D2_UaFXPi5dG-IkC9yLdg8sv9qkyV2eTlZhu5bJrfs0) ![T@K$N71AXM1X%X75$~0BSF2](https://private-user-images.githubusercontent.com/161548283/329753217-5d6b1dfc-b017-4c2f-b766-06b1928e6d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODE4MzIsIm5iZiI6MTcxNTU4MTUzMiwicGF0aCI6Ii8xNjE1NDgyODMvMzI5NzUzMjE3LTVkNmIxZGZjLWIwMTctNGMyZi1iNzY2LTA2YjE5MjhlNmQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNjI1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODQzNjc0NzhiYWE4OTA1MWU2Njg0NDdhZTgwMDQ0YmMwODVkMGRjNDU3YTU3ZGUzYWIzMWE1NDJhNTNjZWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zaYNU9PhJGf2DIoaJf2g3EDW-47fgmQ_Jsync1wBLz0) 这个set cookie好像有两个，我两个都试了，都不起作用。然后请求表头和响应表头的set-cookie和cookie都试过了都不行，是哪里出错了？
> 
> The solution to the problem that the model cannot be downloaded is simply that some models on the civitai website have been set by the author to download only to logged-in users. You need to manually fill in the token of your account after the download link. You can use Google to learn how to apply for civitai users token. ▼this is the solution [#47 (comment)](https://github.com/s4afa451dgf415f/colab_stable_diffusion/issues/47#issuecomment-2053672958)

Thanks.I will try it.
